server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;

  root /opt/zkgl/current/apps/web/dist;
  index index.html;

  add_header X-Robots-Tag "noindex, nofollow" always;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
    expires 10m;
    add_header Cache-Control "public, max-age=600";
    try_files $uri =404;
  }
}
