<script setup lang="ts">
import{onMounted,ref}from'vue';import{callApi}from'../api'
interface Department{id:string;code:string;name:string;status:string}interface Employee{id:string;employeeCode:string;name:string;departmentName:string;positionName?:string;accountStatus:string}interface Role{id:string;name:string}interface User{id:string;username:string;employeeName:string;roleNames?:string;roleIds?:string}
const departments=ref<Department[]>([]),employees=ref<Employee[]>([]),roles=ref<Role[]>([]),users=ref<User[]>([]),error=ref<string|null>(null),saving=ref(false),department=ref({code:'',name:''}),employee=ref({employeeCode:'',name:'',employeeType:'EMPLOYEE',departmentId:'',positionName:'',mobile:'',email:'',joinedOn:''})
async function load(){error.value=null;try{const data=await callApi<{departments:Department[];employees:Employee[];roles:Role[];users:User[]}>('admin.overview',{});departments.value=data.departments;employees.value=data.employees;roles.value=data.roles;users.value=data.users}catch(e){error.value=e instanceof Error?e.message:'加载失败'}}onMounted(load)
async function createDepartment(){saving.value=true;try{await callApi('admin.department.create',department.value);department.value={code:'',name:''};await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{saving.value=false}}
async function createEmployee(){saving.value=true;try{const f=employee.value;await callApi('admin.employee.create',{...f,positionName:f.positionName||null,mobile:f.mobile||null,email:f.email||null,joinedOn:f.joinedOn||null});employee.value={employeeCode:'',name:'',employeeType:'EMPLOYEE',departmentId:'',positionName:'',mobile:'',email:'',joinedOn:''};await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{saving.value=false}}
async function setRoles(user:User,event:Event){const values=Array.from((event.target as HTMLSelectElement).selectedOptions).map(x=>x.value);try{await callApi('admin.user.role.set',{userId:user.id,roleIds:values});await load()}catch(e){error.value=e instanceof Error?e.message:'授权失败'}}
</script>
<template><main class="page"><header class="page-header"><div><p class="eyebrow">SYSTEM ADMINISTRATION</p><h1>系统管理</h1></div></header><p v-if="error" class="error">{{error}}</p><section class="contract-panels"><article><p>部门</p><strong>{{departments.length}}</strong></article><article><p>人员</p><strong>{{employees.length}}</strong></article><article><p>账号</p><strong>{{users.length}}</strong></article><article><p>角色</p><strong>{{roles.length}}</strong></article></section><form class="entity-form" @submit.prevent="createDepartment"><h2 class="wide">新增部门</h2><label>部门编码<input v-model="department.code" required minlength="2"></label><label>部门名称<input v-model="department.name" required minlength="2"></label><button :disabled="saving">保存部门</button></form><form class="entity-form" @submit.prevent="createEmployee"><h2 class="wide">新增人员</h2><label>人员编码<input v-model="employee.employeeCode" required></label><label>姓名<input v-model="employee.name" required></label><label>类型<select v-model="employee.employeeType"><option value="EMPLOYEE">员工</option><option value="PARTNER">合作人</option><option value="EXTERNAL">外部人员</option></select></label><label>部门<select v-model="employee.departmentId" required><option value="" disabled>请选择</option><option v-for="d in departments" :key="d.id" :value="d.id">{{d.name}}</option></select></label><label>岗位<input v-model="employee.positionName"></label><label>手机<input v-model="employee.mobile"></label><label>邮箱<input v-model="employee.email" type="email"></label><label>入职日<input v-model="employee.joinedOn" type="date"></label><button :disabled="saving">保存人员</button></form><section class="data-list"><h2>账号角色</h2><article v-for="u in users" :key="u.id" class="data-row"><div><strong>{{u.employeeName}} · {{u.username}}</strong><p>{{u.roleNames||'未授权'}}</p></div><select multiple :value="u.roleIds?.split(',')||[]" @change="setRoles(u,$event)"><option v-for="r in roles" :key="r.id" :value="r.id">{{r.name}}</option></select></article></section></main></template>
