<script setup lang="ts">
import{onMounted,ref}from'vue';import{callApi}from'../api';import{useAuthStore}from'../stores/auth'
const modules = [['启动', '正常/提前启动'], ['阶段计划', '目标、工期与交付物'], ['进展', '完成情况与偏差'], ['问题风险', '处理与验证闭环'], ['项目变更', '工期及金额影响'], ['成果', '版本提交与确认'], ['验收', '验收结果与整改']]
interface Project{id:string;projectName:string};const auth=useAuthStore(),projects=ref<Project[]>([]),summary=ref({stageCount:0,averageProgress:0,openRiskCount:0,confirmedDeliverableCount:0}),error=ref<string|null>(null),showForm=ref(false),saving=ref(false);const today=new Date().toISOString().slice(0,10),later=new Date(Date.now()+30*86400000).toISOString().slice(0,10);const form=ref({projectId:'',stageName:'',stageOrder:1,plannedStartOn:today,plannedEndOn:later,objective:'',deliverables:''});async function load(){try{const[s,p]=await Promise.all([callApi<typeof summary.value>('delivery.summary',{}),callApi<{items:Project[]}>('project.list',{page:1,pageSize:50})]);summary.value=s;projects.value=p.items}catch(e){error.value=e instanceof Error?e.message:'加载失败'}};onMounted(load);async function createStage(){if(!auth.user)return;saving.value=true;error.value=null;try{await callApi('project.stage.create',{...form.value,ownerId:auth.user.employeeId});showForm.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{saving.value=false}}
</script>
<template>
  <main class="page">
    <header class="page-header"><div><p class="eyebrow">PROJECT DELIVERY</p><h1>项目实施</h1></div><button class="primary-action" @click="showForm=!showForm">{{showForm?'取消':'新增阶段'}}</button></header><p v-if="error" class="error">{{error}}</p>
    <section class="contract-panels"><article><p>阶段计划</p><strong>{{summary.stageCount}}</strong><small>平均进度 {{summary.averageProgress.toFixed(1)}}%</small></article><article><p>未关闭风险</p><strong>{{summary.openRiskCount}}</strong><small>问题与风险</small></article><article><p>已确认成果</p><strong>{{summary.confirmedDeliverableCount}}</strong><small>版本化成果</small></article></section>
    <form v-if="showForm" class="entity-form" @submit.prevent="createStage"><label>项目<select v-model="form.projectId" required><option value="" disabled>请选择</option><option v-for="p in projects" :key="p.id" :value="p.id">{{p.projectName}}</option></select></label><label>阶段名称<input v-model="form.stageName" required></label><label>顺序<input v-model.number="form.stageOrder" type="number" min="1" required></label><label>计划开始<input v-model="form.plannedStartOn" type="date" required></label><label>计划结束<input v-model="form.plannedEndOn" type="date" required></label><label class="wide">阶段目标<textarea v-model="form.objective" required></textarea></label><label class="wide">交付物<textarea v-model="form.deliverables" required></textarea></label><button :disabled="saving">{{saving?'保存中…':'保存阶段'}}</button></form>
    <section class="delivery-timeline">
      <article v-for="([title, detail], index) in modules" :key="title"><span>{{ index + 1 }}</span><div><h2>{{ title }}</h2><p>{{ detail }}</p></div></article>
    </section>
  </main>
</template>
