<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { callApi } from '../api'
import { cloudbaseApp } from '../cloudbase'

interface Project{id:string;projectName:string}
interface FileItem{id:string;logicalName:string;originalName:string;classification:string;sizeBytes:number;uploadedAt:string}
const projects=ref<Project[]>([]),projectId=ref(''),items=ref<FileItem[]>([]),selected=ref<File|null>(null),classification=ref<'INTERNAL'|'SENSITIVE'>('INTERNAL'),loading=ref(false),error=ref<string|null>(null)
onMounted(async()=>{try{projects.value=(await callApi<{items:Project[]}>('project.list',{page:1,pageSize:50})).items}catch(e){error.value=e instanceof Error?e.message:'加载失败'}})
async function load(){if(!projectId.value){items.value=[];return}loading.value=true;error.value=null;try{items.value=(await callApi<{items:FileItem[]}>('file.list',{businessType:'PROJECT',businessId:projectId.value})).items}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function upload(){const file=selected.value;if(!file||!projectId.value)return;loading.value=true;error.value=null;try{const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join('');const prepared=await callApi<{id:string;storageKey:string}>('file.upload.prepare',{businessType:'PROJECT',businessId:projectId.value,projectId:projectId.value,logicalName:file.name,originalName:file.name,mimeType:file.type||'application/octet-stream',sizeBytes:file.size,sha256:hash,classification:classification.value});const uploaded=await cloudbaseApp.uploadFile({cloudPath:prepared.storageKey,fileContent:file});await callApi('file.upload.complete',{fileId:prepared.id,cloudFileId:uploaded.fileID});selected.value=null;await load()}catch(e){error.value=e instanceof Error?e.message:'上传失败'}finally{loading.value=false}}
async function download(id:string){error.value=null;try{const result=await callApi<{url:string}>('file.download',{fileId:id});window.open(result.url,'_blank','noopener,noreferrer')}catch(e){error.value=e instanceof Error?e.message:'下载失败'}}
</script>

<template><main class="page"><header class="page-header"><div><p class="eyebrow">PRIVATE FILES</p><h1>项目文件</h1></div></header><p v-if="error" class="error">{{error}}</p><section class="entity-form"><label>项目<select v-model="projectId" required @change="load"><option value="" disabled>请选择</option><option v-for="p in projects" :key="p.id" :value="p.id">{{p.projectName}}</option></select></label><label>密级<select v-model="classification"><option value="INTERNAL">内部</option><option value="SENSITIVE">敏感</option></select></label><label class="wide">选择文件<input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.gif,.webp,.zip" @change="selected=($event.target as HTMLInputElement).files?.[0]??null"></label><button :disabled="loading||!selected||!projectId" @click="upload">{{loading?'处理中…':'上传文件'}}</button></section><section class="data-list"><article v-for="f in items" :key="f.id" class="data-row"><div><strong>{{f.logicalName}}</strong><p>{{f.originalName}} · {{(Number(f.sizeBytes)/1024).toFixed(1)}} KB · {{f.classification}}</p></div><button class="secondary-button" @click="download(f.id)">下载</button></article><p v-if="projectId&&!loading&&!items.length">暂无文件</p></section></main></template>
